
-- --------------------------------------------------------

--
-- Table structure for table `quiz`
--

DROP TABLE IF EXISTS `quiz`;
CREATE TABLE IF NOT EXISTS `quiz` (
  `id` int NOT NULL AUTO_INCREMENT,
  `question` varchar(500) NOT NULL,
  `options` text,
  `answer` int DEFAULT '0',
  `category` int DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=221 DEFAULT CHARSET=latin1;

--
-- Truncate table before insert `quiz`
--

TRUNCATE TABLE `quiz`;
--
-- Dumping data for table `quiz`
--

INSERT DELAYED IGNORE INTO `quiz` (`id`, `question`, `options`, `answer`, `category`) VALUES
(1, 'Full form of CPR?', 'Cardiopulse Restriction$$Cardiopulmonary Respiration$$Cardiopulmonary Resuscitation$$Cardiac Resustitation', 3, 1),
(2, 'Full form of OHS?', 'Occupation Health & Service$$Occupational Health & Safety$$Occupying Health & Safety$$Ordinary Health & Safety', 2, 1),
(3, 'What is the full form of PTW?', 'Permission  To Work$$Practice To Work$$Permit To Work$$None of the above', 3, 1),
(4, 'What is the number of Fire Brigade?', '100$$101$$102$$108', 2, 1),
(5, 'What is hazard?', 'Anything with the potential to cause harm$$where an accident is likely to cause harm$$The likely hood of something going wrong$$An accident waiting to happen', 1, 1),
(6, 'Accidents are best prevented by?', 'The OHS Executive$$Employers inspecting workplace$$People being aware of hazards and working in a safe manner$$The Managing Director', 3, 1),
(7, 'When should you carry out a visual inspection of the electrical equipment you are using?', 'Before each use$$At the end of the day$$Once a week$$Every few weeks', 1, 1),
(8, 'Where should you aim a fire extinguisher nozzle when putting out a fire?', 'At the top of the fire$$At the base of the fire$$At the centre of the fire$$Away from the fire', 2, 1),
(9, 'Which Day is celebrated as\" National Safety Day\"?', '22 march$$05 june$$04 March$$10 may', 3, 2),
(10, 'Fire consists of three elements:Fuel, Heat & _________', 'Carbon Dioxide$$Petrol$$Wood$$Oxygen', 4, 1),
(11, 'Which  are the  example of OHS/ EHS violation?', 'Field teams working at site without PTW approval$$Field teams working at site without wearing PPE\'s$$Field team working at site without FARM certification$$None of the above$$Options (A), (B) & (C)', 5, 1),
(12, 'CPR involves:-', 'Rescue breaths and abdominal thrusts$$chest compression and rescue breaths$$Chest compression and abdominal thrusts$$Abdominal thrusts & finger sweeps', 2, 1),
(13, 'CPR should only be applied when there is _____________________?', '(a) no heart beat$$(b) no sign of respiration$$Both (a) & (b)$$None of the options - (a) & (b)', 3, 1),
(14, 'While an earthquake is taking place you should?', 'Stop, Drop and Roll$$Drop, Cover and Hold on', 2, 1),
(15, 'What to do when cloth catches fire?', 'Stop, Drop and Roll$$Drop, Cover and Hold on', 1, 1),
(16, 'Which of the following is the acronym describing the correct sequence of using a fire extinguisher?', 'PULL$$PUSH$$PASS$$None of the above', 3, 1),
(17, 'Even when there are no signs of a fire, you should respond to every fire alarm as if it were real?', 'TRUE$$FALSE', 1, 1),
(18, 'Before an emergency occurs, you should ...........', 'Be able to recognise the sound/ signal of a fire or evacuation alarm$$know the person to contact in an emergency$$Be aware of the path ways to a minimum of 2 exits from every area of the work place$$All of the above', 4, 1),
(19, 'Under the health & safety act Work Act etc, 1974 which of the following have a duty to work safely?', 'Employers only$$Employees only$$The general public$$All people at work', 4, 1),
(20, 'ABC type fire extinguisher is applied for which type of fire?', 'Wood, Paper$$Grease, Oil, Fuel$$Acetylene, Natural gas$$All of the above', 4, 1),
(21, 'What not to do if you find any hazard at your work place?', 'Inform OHS/EHS department$$take control measure$$Warn other members of the work place$$Leave it as it is because its not your responsibility', 4, 1),
(22, 'What not to do when a person is unconsciousafter the electrical shock?', 'Call ambulance$$Sprinkle water on the victim body$$CPR process$$Inform senior management', 2, 1),
(23, 'If a person is ill or got injured or being unconscious at the work place then what not to do?', 'Call ambulance$$Ask the victim not to get nervous$$Provide necessary First Aid$$Give medicines to the victim', 4, 1),
(24, 'Which day is celebrated as\"World Environment Day\" ?', '4th March$$22nd April$$22nd March$$5th June', 4, 2),
(25, 'Who has responsibility for Health and Safety at your work place?', 'The Client and main contractor only$$Self employed and contractors only and employees$$Employers, Employees and sub-contractors$$Everyone at your work place no matter who employs them', 4, 1),
(26, 'Which of the following is correct for the risk assessment?', 'It is a good idea to do, but not essential$$Only to do it if the job is a big job$$It is a legal requirement and must always be carried out prior to starting the job$$Only needs to be done for the hazardous work', 3, 1),
(27, 'Full form of PPE ?', 'Personnel Perspective Equipment$$Personal Protective Equipment$$Personal Protective Environment$$Personal Preventive Equipment', 2, 1),
(28, 'What is\"Risk Level\" in Risk Assessment?', 'Residual risk * Probability$$Severity * GRA$$Probability * Severity$$None of the above', 3, 1),
(29, 'When to start activity at site?', 'After team members suggestion$$Immediately after reaching at site$$Before PTW Approval$$After PTW Approval', 4, 1),
(30, 'What is the severity rate for\" superficial injury\"?', '4$$5$$1$$3', 3, 1),
(31, 'What is the severity rate for\"Fatal injury\"?', '4$$5$$3$$1', 2, 1),
(32, 'CPR should only be performed when a person is _____________________?', '(a) Unresponsive$$(b) Unconscious$$(c) not breathing or not breathing normally$$All options - (a), (b) & (c)$$None of the options - (a), (b), (c)', 4, 1),
(33, 'Who is the Prime Minister of India?', 'Amit Shah$$Narendra Modi$$Ram Nath Kovind$$Pranab Mukherjee', 2, 2),
(34, 'Who is the President of India?', 'Narendra Modi$$Pratibha Patil$$Ram Nath Kovind$$Pranab Mukherjee', 3, 2),
(35, 'Who is the Finance Minister of India?', 'Amit Shah$$Nirmala Sitharaman$$Arun Jaitley$$P. Chidambaram', 2, 2),
(36, 'Full form of LAN?', 'Large Area Network$$Local Area Network$$Local Area Net$$Locality And Network', 2, 3),
(37, 'Full form of FARM TO-CII?', 'Fall Arrest and Refresher Management To Climer$$Fresher And Refresher Management Tower Climer$$Fall Arrest and Rescue Manangement- Tower Climber$$Fight And Rescue Management Tower Climer', 3, 1),
(38, 'Full form of TBT?', 'Telecom Base Tower$$Tool Box Talk$$Time Base Task$$Tool Box Task', 2, 1),
(39, 'Full form of GRA?', 'Group Responsible Assisstant$$Ground Risk Assessment$$Group Risk Assessment$$Great Risk Assessment', 3, 1),
(40, 'Total number of Nokia life saving rules?', '10$$9$$6$$5', 3, 1),
(41, 'Total number of Huawei EHS Absolute rules?', '10$$9$$6$$5', 1, 1),
(42, 'Total number of  Vodafone Absolute safety rules?', '10$$9$$6$$5', 2, 1),
(43, 'Which is an example of \"Near Miss\"?', '5 people got injured in road accident$$one technician was injured after falling from height$$Site engineer working  without PTW at site?$$An incident happened but no property damage or personal injury took place', 4, 1),
(44, 'Which  are the  example of OHS/ EHS violation?', 'Field teams working at site without PTW approval$$Field teams working at site without wearing PPE\'s$$Field team working at site without FARM certification$$None of the above$$Options (A), (B) & (C)', 5, 1),
(45, 'On which side people should walk on road?', ' Right$$Left$$Middle $$pedestrain\'s wish', 2, 1),
(46, 'Full form of CAPA?', 'Capability and Protective Action$$Corrective Action and Preventive Action$$Circle Administration and Project Admin$$Corrective Action and Protection Action', 2, 1),
(47, 'Full form of GBT?', 'Gravity Based Tower$$Ground Based Tower$$Great Built Tower$$Ground Built Tower', 2, 1),
(48, 'Full form of \"RTT\" ?', 'Roof Top Tower$$Round Tilt Tower$$Range to Tower$$Risk To Tower', 1, 1),
(49, 'What do you mean by \"Work At height\"?', 'activty above ground level at 3m$$activity below ground level at 4m$$activity above 1.8m$$None of the above$$Options (A), (B) & (C)', 5, 1),
(50, 'Which standard PPE\'s are used?', 'AN$$EN$$PN$$UN', 2, 1),
(51, 'What is the lenghth of lanyard in full body safety harness?', '1m$$2m$$3m$$4m', 2, 1),
(52, 'What is the length of Energy/Shock Absorber in full body safety harness?', '1.2 m$$2.0 m$$2.2m$$3m', 1, 1),
(53, 'Benefits of using \"Work positioning lanyard\"?', 'Provides support to position yourself at height activity$$Makes its possible to work with both hands free$$easy to use in lifting materials$$None of the above$$Options (A) and (B)', 5, 1),
(54, 'Full form of SWL?', 'Site Work Load$$System Working Load$$Safe Working Load$$Safety Works Limited', 3, 1),
(55, 'celebrated as \" Republic day of India\"?', '2nd OctoberWhich day is cel$$15th August$$26th January$$14th November', 3, 2),
(56, 'Which day is celebrated as \" Independence day of India\"?', '14th February$$15th August$$26th January$$14th November', 2, 2),
(57, 'What do you mean by  \"Emergency Assembly Point\"?', 'Friends Meeting place in emergency$$Office staffs meeting place  in emergency $$ safe place where all should come during an emergency in office, site or public area$$Place where installation assemble work is done', 3, 1),
(58, 'what is the full form of \"SOP\"?', 'Safe Operation Process$$Standard Operating Procedure$$Standard of Person$$Site Optimization Process', 2, 1),
(59, ' FARM TO-CLI training certificate is valid for …………………?', '1 yr$$2 yr$$3 yr$$Lifetime', 2, 1),
(60, ' FARM Refresher training certificate is valid for …………………?', '1 yr$$2 yr$$3 yr$$Lifetime', 2, 1),
(61, 'Medical certificate is valid for ………….?', '1 yr$$2 yr$$3 yr$$Lifetime', 1, 1),
(62, 'First Aid training certificate is valid for …………….?', '1 yr$$2 yr$$3 yr$$Lifetime', 2, 1),
(69, 'How many days does a leap year have ?', '364$$365$$366$$367$$None of the above', 3, 2),
(70, 'What is the full form of \"NASA\"?', 'National Aeronautics and Space Administration$$North Asia and South Asia$$North Administration and South Administration$$None of the above', 1, 2),
(71, 'What is the full of \"ISRO\"?', 'India Safe Railway Organisation$$Indian Space Research Organisation$$India Supporting Ruling Organisation$$None of the above', 2, 2),
(72, 'What is the full of \"TRAI\"?', 'Telecom Regulatory Authority of India$$Transportation Railways Administration of India$$None of the above', 1, 2),
(73, 'Why an activated shock absorbing lanyard must never be used again?', 'It can be used again$$It will not absorb shock load again$$Because trainer says not to use again$$None of the above', 2, 1),
(74, 'What to do if \"Energy absorber \" found defective during safety harness inspection?', 'Use cellotapes to fix and hide the defect$$Nothing to do and leave as it is$$Defective Energy absorber need to be replaced with new one$$Safety harness should not be used untill defective energy absorber is changed with new $$Options © & (D)', 5, 1),
(75, 'Why chin strap is provided in a safety helmet?', 'To make the helmet more costly$$to easily hang the helmet anywhere $$To keep the helmet on the worker\'s head during a fall, site activity or in high wind conditions$$Unnecessary provided in the safety helmet', 3, 1),
(76, 'What are the responsibilities of a site engineer/ supervisor ?', 'Team members must start activity only after PTW approval$$Observing Clamping to tower from start to end of the height activity by his team members at site $$No team member should work without any mandatory PPE\'s at site$$To ensure the fall protection plan is implemented$$All options (A), (b), © & (D)', 5, 1),
(77, 'Why must first aid be applied as soon as possible?', 'To calm the patient$$To use the fist aid  kit before it expires$$To prevent the patient\'s condition from worsening$$None of the above', 3, 1),
(78, 'India is a ……………………?', 'State$$Country$$Continent$$Union Territory', 2, 2),
(79, 'Europe is a ……………………?', 'State$$Country$$Continent$$Union Territory', 3, 2),
(80, 'Australia is a ……………………?', 'State$$Country$$Continent$$Union Territory', 3, 2),
(81, 'Africa is a ……………………?', 'State$$Country$$Continent$$Union Territory', 3, 2),
(82, 'Asia is a ……………………?', 'State$$Country$$Continent$$Union Territory$$None of these', 3, 2),
(83, 'North America is a …………………?', 'State$$Country$$Continent$$Union Territory$$None of these', 3, 2),
(84, 'South America is a ………………?', 'State$$Country$$Continent$$Union Territory$$None of these', 3, 2),
(85, 'Antarctica is a ………………….?', 'State$$Country$$Continent$$Union Territory$$None of these', 3, 2),
(86, 'Capital of Andaman and Nicobar Islands?', 'Chandigarh$$Daman$$Pondicherry$$Port Blair', 4, 2),
(87, 'Capital of Lakshadweep?', 'Kavaratti$$Daman$$Pondicherry$$Port Blair', 1, 2),
(88, 'Capital of Arunachal Pradesh ?', 'Hyderabad$$Assam$$Itanagar$$Shimla', 3, 2),
(89, 'Capital of Assam?', 'Itanagar$$Panaji$$Kavaratti$$Dispur', 4, 2),
(90, 'Capital of Chattisgarh ?', 'Panaji$$Dispur$$Raipur$$Itanagar', 3, 2),
(91, 'Capital of Goa?', 'Daman$$Panaji$$Diu$$Pondicherry', 2, 2),
(92, 'Capital of Gujarat?', 'Ahmedabad$$Porbandar$$Gandhinagar$$Surat', 3, 2),
(93, 'Capital of Haryana?', 'Gurugram$$Chandigarh$$Ambala$$Karnal', 2, 2),
(94, 'Capital of Himachal Pradesh?', 'Manali$$Shimla$$Dharamshala$$Dalhouise', 2, 2),
(95, 'Capital of Karnataka?', 'Hyderabad$$Amravati$$Bengaluru$$Vishakhapatnam', 3, 2),
(96, 'Capital of Kerala?', 'Hyderabad$$Bengaluru$$Bangalore$$Thiruvananthapuram', 4, 2),
(97, 'Capital of Telangana?', 'Bangalore$$Hyderabad$$Thiruvananthapuram$$Kerala', 2, 2),
(98, 'Capital of Uttar Pradesh?', 'Kanpur$$Varanasi$$Lucknow$$Prayagraj', 3, 2),
(99, 'Capital of Tamil Nadu?', 'Chennai$$Bengaluru$$Kerala$$Hyderabad', 1, 2),
(100, 'Capital of Punjab?', 'Ludhiana$$Chandigarh$$Ambala$$Amritsar', 2, 2),
(101, 'The responsibility for Fire Prevention belongs to ……………………', 'Managers$$Supervisors$$Everyone$$Fire Department', 3, 1),
(102, 'In the event of the Fire Alarm I should ……………………….', 'Move to the back of the building$$Leave the building immediately$$Keep working and not worry about it$$Report it within a week', 2, 1),
(103, 'For the fire to start, there must be …………………………………………..', 'Fuel$$A heat source$$Oxygen$$All of the above', 4, 1),
(104, 'I can prevent electrical fires by ………………………………………', 'Not turning on lights$$Never plugging anything into an outlet$$Both (a) & (b)$$Not overloading an electrical circuits', 4, 1),
(105, 'If you see a fire hazard you should ……………………………….', 'Report it as a safety hazard$$Discuss it at the next safety meeting$$Tell a co-worker$$None of the above', 1, 1),
(106, 'Employees who work on or repair electrical equipment ………………….', 'are volunteers$$are trained and authorized$$cannot work on other equipment$$None of the above', 2, 1),
(107, 'Electrical Shock can cause ……………………………', 'Hearing Loss$$Death$$Blindness$$Chemical Sensitivity', 2, 1),
(108, 'If you see bare or exposed wires you should ……………………', 'wrap them in tape$$warn others and report it to a supervisor$$cut the wires to prevent a fire$$Both (a) & ©', 2, 1),
(109, 'Before using electrical tools ………………..', 'check the rating on the label$$check for broken parts$$check that the handle is black$$All of the above', 2, 1),
(110, 'Voltage at or above which value below is considered hazardous?', '10 volts$$30 volts$$110 volts$$240 volts', 2, 1),
(111, 'Before plugging in an electrical tool or appliance …………….', 'check for broken plug$$check for exposed wires$$don\'t overload an outlet$$All of the above', 4, 1),
(112, 'If you see a lock or tag on an electrical switch …………', 'you can turn on the switch if it is your equipment$$it is ok to use the euipment if no one is working on it$$You must not touch the switch$$None of the above', 3, 1),
(113, 'Labels on chemical  containers ………………...', 'Tell me basic safety and use information$$are not required$$provide all the information I need$$come in many colors', 1, 1),
(114, 'If I use chemicals at work I must ……………………….', 'be very careful$$never work alone$$wear a respirator$$be specifically trained and authorized', 4, 1),
(115, 'The correct Personal Protective Equipment can ………..', 'Be used when I want to $$Protect me from hazards$$cause skin irritation$$make me work slower', 2, 1),
(116, 'On the multi-colored chemical label, Blue represents …………..', 'Fire hazard$$Health Hazard$$Reactivity Hazard$$Personal Protective Equipment', 2, 1),
(117, 'On the multi-colored chemical label, Red represents …………..', 'Fire hazard$$Health Hazard$$Reactivity Hazard$$Personal Protective Equipment', 1, 1),
(118, 'On the multi-colored chemical label, White represents …………..', 'Fire hazard$$Health Hazard$$Reactivity Hazard$$Special hazards', 4, 1),
(119, 'On the multi-colored chemical label, Yellow represents …………..', 'Fire hazard$$Health Hazard$$Reactivity Hazard$$Special hazards', 3, 1),
(120, 'Spills of chemicals should be ………………….', 'cleaned up by trained employees$$reported immediately$$prevented by using seal containers$$All of the above', 4, 1),
(121, 'Is COVID-19 th same as the SARS virus or MERS?', 'Yes$$No', 2, 4),
(122, 'Does COVID-19 spread from person to person?', 'Yes$$No', 1, 4),
(123, 'Is there any vaccine to cure Coronavirus ?', 'Yes$$No', 2, 4),
(124, 'World Health Organisation on 11 February, 2020 announced an official name for the disease that is causing the 2019 novel coronavirus outbreak.  What is the new name of the disease?', 'COVID-19$$COVn-19$$CONV-20$$COnVID-20', 1, 4),
(125, 'The first case of nobel coronavirus was identified in ……..?', 'Beijing$$Shanghai$$Wuhan, Hubei$$Tianjin', 3, 4),
(126, 'Which are the following diseases related to coronavirus?', 'MERS$$SARS$$Both (a) & (b)$$None of the above', 3, 4),
(127, 'Mild symptoms of Novel coronavirus are:', 'Fever$$Cough$$Shortness of breath$$All of the above', 4, 4),
(128, 'From where coronavirus got its name?', 'Due to their crown like projections$$Due to their leaf-life projections$$Due to their surface structure of bricks$$None of the above', 1, 4),
(129, ' What are the precautions that need to be taken to protect from the coronavirus?', 'Cover your nose and mouth when sneezing.$$Avoid touching your eyes, nose and mouth $$Use an alcohol based hand senitizer$$Wash your hands frequently with soap and water for at least 20 seconds $$All options (A), (b), © & (D)', 5, 4),
(130, 'Which of the following coronaviruses has caused thousands of deaths around the world as an \'emergent\' virus?', 'MERS$$SARS$$OC43$$HKU1', 2, 4),
(131, 'What is the full form of \"MERS\" coronavirus?', 'Microscopic Endocrine Resistant Syndrome$$Middle East Respiratory Syndrome$$None of the above', 2, 4),
(132, 'What is the full form of \"SARS\" coronavirus?', 'Severe Acute Respiratory Syndrome$$Staphylococcus Aureus Resistant Syndrome$$None of the above', 1, 4),
(133, 'How does Coronavirus transmit?', 'When a person sneezes or cough, droplets spread in the air or fall on the ground and nearby surfaces.$$If another person is nearby and inhales the droplets or touches these surfaces and further touches his face, eyes or mouth, he or she can get an infection.$$If the distance is less than 1 meter from the infected person.$$All of the above', 4, 4),
(134, 'Is coronavirus contagious?', 'Yes$$No', 1, 4),
(135, 'Can hand dryers kill coronavirus?', 'Yes$$No', 2, 4),
(136, 'Coronavirus can enters throgh which part of the body?', 'Eyes$$Nose$$Mouth$$All of the above', 4, 4),
(137, 'Is it safe to travel to China or other countries where COVID-19 cases have occurred?', 'Yes$$No', 2, 4),
(138, 'Coronavirus is more dangerous to which type of people?', 'Older persons$$Heart patient$$High blood pressure patient$$Diabetes patient$$All of the above', 5, 4),
(139, 'Is drinking alcohol can reduce the chances of getting infected from coronavirus?', 'Yes$$No', 2, 4),
(140, 'Does putting on sesame oil block the new coronavirus from entering the body?', 'Yes$$No', 2, 4),
(141, 'What should be the minimum distance  while communication with sick people?', '1 m$$10 m$$No need to talk untill the person gets well$$None of the above', 1, 4),
(142, 'What people should  do who have returned from travelling an area where COVID-19 is spreading ?', 'Should monitor themselves for symptoms for 14 days $$take their temperature twice a day $$Both (a) & (b)$$None of the above', 3, 4),
(143, 'Is it safe to receive a package from any area where COVID-19 has been reported?', 'Yes$$No', 1, 4),
(144, 'How long is the incubation period for COVID-19?', '1-14 days$$48 hours$$24 hours$$None of the above', 1, 4),
(145, 'Are antibiotics effective in preventing or treating the COVID-19? ', 'Yes$$No', 2, 4),
(146, 'What’s the shortcut for the “copy” function on most computers?', 'ctrl S$$ctrl C$$ctrl A$$ctrl X', 2, 2),
(147, 'Which crop is sown on the largest area in India?', 'Rice$$Wheat$$Sugarcane$$Maize', 1, 2),
(148, 'Grand Central Terminal, Park Avenue, New York is the world\'s', 'highest railway station$$longest railway station $$largest railway station$$None of the above', 3, 2),
(149, 'The world smallest country is', 'Canada$$Russia$$Maldives$$Vatican City', 4, 2),
(150, 'What is the second largest country (in size) in the world?', 'Canada$$USA $$China$$Russia', 1, 2),
(151, 'Which language is spoken in Karnataka?', 'Marathi$$Hindi$$Malayalam$$Kannada', 4, 2),
(152, 'Ball pen function on which one of the following principal?', 'Boyle’s law$$Gravitational force$$Surface tension$$Viscosity', 3, 2),
(153, 'The state which has the largest number of sugar mills in India is', 'Bihar$$Haryana$$Punjab$$Uttar Pradesh', 4, 2),
(154, 'Who invented the internet?', 'Robert E. Kahn and Vint Cerf$$Philip Diehl$$William Sturgeon$$Frederick Banting', 1, 2),
(155, 'Who invented the FM radio?', 'Edwin Howard Armstrong$$Edward Henrik Armstrong$$Louis Theroux$$Adam Anter', 1, 2),
(156, 'Who invented the telephone?', 'J.L Baird$$Alexander Graham Bell $$Marconi$$James Dewar', 2, 2),
(157, 'Who invented the railway engine?', 'Charles Babbage$$Isaac Newton$$James Watt$$George Stephenson', 4, 2),
(158, 'Which scientist discovered the radioactive element radium?', 'Isaac Newton$$Albert Einstein$$Benjamin Franklin$$Marie Curie', 4, 2),
(159, 'Microprocessor was invented by', 'Alfred Nobel$$Federico Faggin$$Zacharias Janssen$$Percy Spencer', 2, 2),
(160, 'Who among the following invented the Email?', 'Ralph H. Baer$$Vint Cerf$$Steve Jobs$$Shiva Ayyadurai', 4, 2),
(161, ' What does the abbreviation WWW stand for?', 'World Wide Web$$World World Web$$World Wide World$$World Web Web', 1, 2),
(162, 'Who hosts the flag on Independence Day at Delhi Fort?', 'President$$Chief Justice$$Prime Minister$$Vice President', 3, 2),
(163, 'Abdul Kalam Azad became the ____ President of India.', '9th$$10th$$11th$$12th', 3, 2),
(164, 'Supreme Court Judges retire upon attaining the age of', '65 years$$62 years$$68 years$$70 years', 1, 2),
(165, 'Who was the first female to become the governor of an Indian state?', 'Subba Lakshmi$$Padmaja Naidu$$Sarojini Naidu$$Vijaya Lakshmi Pandit', 3, 2),
(166, 'The main source of water pollution is', 'Sewage Water$$Rain water$$Atmospheric Pollutants$$Well Water', 1, 2),
(167, 'Which of the following problems is not created by noise pollution?', 'Diarrhoea$$Hypertension$$Deafness$$Irritation', 1, 2),
(168, 'National stock exchange is located', 'New Delhi$$Mumbai $$Kolkata$$Bangalore', 2, 2),
(169, 'Where is the headquarter of World Health Organization (WHO)?', 'New York$$Geneva, Switzerland$$Peris $$London', 2, 2),
(170, 'The National Game of India is', 'Cricket$$Football$$Tennis$$Hockey', 4, 2),
(171, 'What does “HTTP” stand for?', 'Hyper Text Transmission Part$$Hyper Text Transfer Protocol$$Hitech Transport Text Protocol$$None of the above', 2, 2),
(172, 'Which email service is owned by Microsoft?', 'Gmail$$Yahoo mail$$Hotmail$$None of the above', 3, 2),
(173, 'Google Chrome, Safari, Firefox and Explorer are different types of what?', 'Web browsers$$Search Engine$$Social Sites$$None of the above', 1, 2),
(174, 'Who is often called the father of the computer?', 'Albert Einstein$$Isaac Newton$$Steve Jobs$$Charles Babbage', 4, 2),
(175, ' Which planet is the hottest in the solar system?', 'Mercury$$Mars$$Venus$$Jupiter', 3, 2),
(176, ' What does BMW stand for (in English)?', 'Brazil Motor Works$$Bavarian Motor Works$$British Mechanic Works$$None of the above', 2, 2),
(177, 'Which element is said to keep bones strong?', 'Iodine$$Iron$$Calcium$$Oxygen', 3, 2),
(178, 'What does the acronym AIDS stand for?', 'All India Deficiency Syndrome$$Acquired Immune Deficiency Syndrome$$Acquired Instant Disease System$$None of the above', 2, 2),
(179, 'Which continent is the largest?', 'Asia$$Africa$$Europe$$Antarctica', 1, 2),
(180, 'In which age group the COVID-19 spreads?', 'COVID-19 occur in all age groups.$$Coronavirus infection is mild in children.$$Older person and persons with pre-existing medical conditions are at high risk to develop serious illness.$$All of the above', 4, 4),
(181, 'What is/are the components of 3 \"R\"s for managing dismantled equipment due to Modernization? ', 'Re-use$$Re-cycle$$Re-check$$Re-sell$$Options (A), (B)& (D)', 5, 3),
(182, 'Which equipment(s) should be worn to avoid ESD while personal grounding?', 'ESD Wrist strap$$Helmet$$Gloves$$Leather shoes', 1, 1),
(183, 'What does ESD stand for?', 'Electrical Surge Discharge$$Electronics Static Device$$Electrostatic Discharge$$Electrical Safety Device', 3, 1),
(184, 'What is meaning of \"E\" in word \"FASTEN\" under \"Work at Height\"?', 'Emergency$$Equipment$$Execution$$Efforts', 2, 1),
(185, 'Does Customer(NOKIA/HUAWEI/others) allow free climbing in rare urgent conditions?', 'Does not matter$$Sometimes$$Always$$Never', 4, 1),
(186, 'What\'s the compliance rate to follow for NOKIA Life Saving rules?', '0.5$$0.7$$1$$Doesn\'t matter', 3, 1),
(187, 'If an accident while working at height, how it should be reported?', 'By making an immediate call $$Filling incident report$$Filling Health & Inspection checklist$$Filling safety checklist$$Options (A) & (B)', 5, 1),
(188, 'What is (are) the benefit(s) of Tool Box Talk(TBT)?', 'Protects Employees$$Reduce injuries$$Increases productivity$$All of the above', 4, 1),
(189, 'What is/are right(s) of the related person if there is a risk to life in  doing any site work?', 'No right, he/she has to do the assigned work$$Can ask additional measures to do the assigned work$$Refuse to Work (RTW)$$Don\'t Know', 3, 1),
(190, 'What is/are the component(s) to be considered under Road safety ?', 'Driver$$Vehicle$$Journey related risks$$All of the above$$None of the above', 4, 1),
(191, 'Which of the following categories is/are applicable under Life saving rules?', 'Road Safety$$Working at height$$Electrical safety$$All of the above', 4, 1),
(192, 'How many categories are covered under NOKIA Life Saving rules?', '2$$3$$4$$5', 2, 1),
(193, 'Which of the following products are offered under Nokia Energy Solutions?', 'FSMF$$FPRB$$FPBC$$Air Scale$$Options (B) & ©', 5, 3),
(194, 'Which of the following activities are performed during physical installation? ', 'Unpacking of material$$Setting up the equipment$$Connecting Power and grounding cables$$Integration$$Options (A), (B) &©', 5, 3),
(195, 'How many person(s) should be involved while running/ routing cables?', '2$$4$$6$$8', 1, 3),
(196, 'Which of the following activties are captured during Physical Site Survey of Radio Site?', 'Space Availability$$Pictures of existing equipment$$Floor Plan & Layouts$$All of the above$$None of the above', 4, 3),
(197, 'How many grounding cable(s) must be connected to BTS?', '1 cable$$3 cables$$4 cables$$can be anything', 1, 3),
(198, 'What is meant by RFI?', 'Ready For Installation$$Radio frequency information$$Ready for inquiry$$None of the above', 1, 3),
(199, 'Which of the following is/are new tool(s) introduced by Nokia for Project execution?', 'NDP Deploy Tool$$NDP Collaborator$$IPM$$Options (A) & (B)$$None of the above', 4, 3),
(200, 'Line of Site Survey is done for which harddware technology?', 'BTS implementation$$MW Implementation$$Core implementation$$None of the above', 2, 3),
(201, 'Which of the following activties is/are covered  in the Telecom implementation portfolio?', 'Site Survey$$Network Planning$$Physical Installation$$Commisioning and Integration$$Options (A), © & (D)', 5, 3),
(202, 'Which of the following document(s) must be there in the As-built information?', 'Approved Technical Site Survey$$Network Data Details$$Connectivity Diagram$$All of the above$$None of the above', 4, 3),
(203, 'Which of the following transmission media is/are supported by Nokia Microwave products?', 'Fronthaul$$Backhaul$$Backbone$$All of the above$$None of the above', 4, 3),
(204, 'Which of the following is current release of hardware introduced by Nokia for 5G?', 'Air Scale$$Ultra$$Flexi Edge$$Flexi Multiradio', 1, 3),
(205, 'What is the minium quantity of hardware modules to build site with Flexi Multiradio BTS?', '1$$2$$3$$4', 2, 3),
(206, 'At which stage module (Hardware) grounding should be done?', 'After Power On$$Before Power On$$No need to do grounding$$Doesn\'t matter', 2, 3),
(207, 'Which form should  be filled for site material shortage?', 'Site Survey Form$$Delivery Challan$$Safety Checklist$$Acceptance Checklist', 2, 3),
(208, 'What is the team composition for  a perfect site survey?', 'Rigger and Technician$$Rigger, Technician and Engineer$$Only Engineer$$Engineer and Technician', 4, 3),
(209, 'When  should one demand for Safety checklist as per Nokia Site Installation MOP?', 'before start of work$$During Implementation$$After Implementation$$can be anything', 1, 1),
(210, 'Is safety checklist same for all countries?', 'Depends on Project Scope$$Don\'t Know$$Yes$$No', 4, 1),
(211, 'When should  the tool list be checked as per Nokia MOP?', 'On site$$before moving to site$$During Installation$$After completion of Installation', 2, 1),
(212, 'MOP is agreed between which of the following stakeholders?', 'Nokia and its Employees$$Nokia and TI partner$$Nokia and Customer$$Nokia and other Equipment Manufacture', 3, 3),
(213, 'What is the full form of MOP?', 'Method of Profit$$Method of Procedure$$Matter of process$$Meeting of Project', 2, 1),
(214, 'What is Customer Acceptance?', 'Self Quality Check$$Customer accepts fault$$External Quality check by Customer$$None of the above', 3, 3),
(215, 'What should be there in \"BTS implementation\" Site quality check list?', 'Check cable routing as per guidelines$$BTS grounding done properly$$Doesn\'t matter$$Delivery package without damage $$Options (B) & (D)', 5, 3),
(216, 'What should  be there in Logistics/ Delivery Site Quality check list?', 'Power cable properly installed$$Material as per Bill of Quantities$$Delivery package without damage $$All of the above$$Options (B) & ©', 5, 3),
(217, 'Who provides Site quality audit checklist?', 'Nokia$$Customer$$Subcontractor$$All of the above', 1, 3),
(218, 'Nokia expects quality as first preference from its Subcontractors?', 'No$$Yes$$Sometimes$$None of the above', 2, 3),
(219, 'For Customer/Nokia what comes first?', 'Work$$Profit$$Quality$$None of the above', 3, 3),
(220, 'Which equipment generates DC power for Nokia Hardware equipment?', 'Power Board$$Power Plant$$Fuse Panel at rack of BTS$$None of the above', 2, 1);
